// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"

	"github.com/dalibortosic00/url-shortener/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLinkStore creates a new instance of MockLinkStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinkStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinkStore {
	mock := &MockLinkStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLinkStore is an autogenerated mock type for the LinkStore type
type MockLinkStore struct {
	mock.Mock
}

type MockLinkStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLinkStore) EXPECT() *MockLinkStore_Expecter {
	return &MockLinkStore_Expecter{mock: &_m.Mock}
}

// GetCodeByURL provides a mock function for the type MockLinkStore
func (_mock *MockLinkStore) GetCodeByURL(ctx context.Context, url string) (string, bool) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for GetCodeByURL")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, bool)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, url)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockLinkStore_GetCodeByURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCodeByURL'
type MockLinkStore_GetCodeByURL_Call struct {
	*mock.Call
}

// GetCodeByURL is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockLinkStore_Expecter) GetCodeByURL(ctx interface{}, url interface{}) *MockLinkStore_GetCodeByURL_Call {
	return &MockLinkStore_GetCodeByURL_Call{Call: _e.mock.On("GetCodeByURL", ctx, url)}
}

func (_c *MockLinkStore_GetCodeByURL_Call) Run(run func(ctx context.Context, url string)) *MockLinkStore_GetCodeByURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkStore_GetCodeByURL_Call) Return(s string, b bool) *MockLinkStore_GetCodeByURL_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockLinkStore_GetCodeByURL_Call) RunAndReturn(run func(ctx context.Context, url string) (string, bool)) *MockLinkStore_GetCodeByURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinksByOwner provides a mock function for the type MockLinkStore
func (_mock *MockLinkStore) GetLinksByOwner(ctx context.Context, ownerID string) ([]models.LinkRecord, error) {
	ret := _mock.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetLinksByOwner")
	}

	var r0 []models.LinkRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.LinkRecord, error)); ok {
		return returnFunc(ctx, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.LinkRecord); ok {
		r0 = returnFunc(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.LinkRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkStore_GetLinksByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinksByOwner'
type MockLinkStore_GetLinksByOwner_Call struct {
	*mock.Call
}

// GetLinksByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
func (_e *MockLinkStore_Expecter) GetLinksByOwner(ctx interface{}, ownerID interface{}) *MockLinkStore_GetLinksByOwner_Call {
	return &MockLinkStore_GetLinksByOwner_Call{Call: _e.mock.On("GetLinksByOwner", ctx, ownerID)}
}

func (_c *MockLinkStore_GetLinksByOwner_Call) Run(run func(ctx context.Context, ownerID string)) *MockLinkStore_GetLinksByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkStore_GetLinksByOwner_Call) Return(linkRecords []models.LinkRecord, err error) *MockLinkStore_GetLinksByOwner_Call {
	_c.Call.Return(linkRecords, err)
	return _c
}

func (_c *MockLinkStore_GetLinksByOwner_Call) RunAndReturn(run func(ctx context.Context, ownerID string) ([]models.LinkRecord, error)) *MockLinkStore_GetLinksByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// LoadLink provides a mock function for the type MockLinkStore
func (_mock *MockLinkStore) LoadLink(ctx context.Context, code string) (*models.LinkRecord, bool) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for LoadLink")
	}

	var r0 *models.LinkRecord
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.LinkRecord, bool)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.LinkRecord); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LinkRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockLinkStore_LoadLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadLink'
type MockLinkStore_LoadLink_Call struct {
	*mock.Call
}

// LoadLink is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockLinkStore_Expecter) LoadLink(ctx interface{}, code interface{}) *MockLinkStore_LoadLink_Call {
	return &MockLinkStore_LoadLink_Call{Call: _e.mock.On("LoadLink", ctx, code)}
}

func (_c *MockLinkStore_LoadLink_Call) Run(run func(ctx context.Context, code string)) *MockLinkStore_LoadLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkStore_LoadLink_Call) Return(linkRecord *models.LinkRecord, b bool) *MockLinkStore_LoadLink_Call {
	_c.Call.Return(linkRecord, b)
	return _c
}

func (_c *MockLinkStore_LoadLink_Call) RunAndReturn(run func(ctx context.Context, code string) (*models.LinkRecord, bool)) *MockLinkStore_LoadLink_Call {
	_c.Call.Return(run)
	return _c
}

// SaveLink provides a mock function for the type MockLinkStore
func (_mock *MockLinkStore) SaveLink(ctx context.Context, record *models.LinkRecord) error {
	ret := _mock.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for SaveLink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.LinkRecord) error); ok {
		r0 = returnFunc(ctx, record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLinkStore_SaveLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveLink'
type MockLinkStore_SaveLink_Call struct {
	*mock.Call
}

// SaveLink is a helper method to define mock.On call
//   - ctx context.Context
//   - record *models.LinkRecord
func (_e *MockLinkStore_Expecter) SaveLink(ctx interface{}, record interface{}) *MockLinkStore_SaveLink_Call {
	return &MockLinkStore_SaveLink_Call{Call: _e.mock.On("SaveLink", ctx, record)}
}

func (_c *MockLinkStore_SaveLink_Call) Run(run func(ctx context.Context, record *models.LinkRecord)) *MockLinkStore_SaveLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.LinkRecord
		if args[1] != nil {
			arg1 = args[1].(*models.LinkRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkStore_SaveLink_Call) Return(err error) *MockLinkStore_SaveLink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLinkStore_SaveLink_Call) RunAndReturn(run func(ctx context.Context, record *models.LinkRecord) error) *MockLinkStore_SaveLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCodeGenerator creates a new instance of MockCodeGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCodeGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCodeGenerator {
	mock := &MockCodeGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCodeGenerator is an autogenerated mock type for the CodeGenerator type
type MockCodeGenerator struct {
	mock.Mock
}

type MockCodeGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCodeGenerator) EXPECT() *MockCodeGenerator_Expecter {
	return &MockCodeGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockCodeGenerator
func (_mock *MockCodeGenerator) Generate(length int) (string, error) {
	ret := _mock.Called(length)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (string, error)); ok {
		return returnFunc(length)
	}
	if returnFunc, ok := ret.Get(0).(func(int) string); ok {
		r0 = returnFunc(length)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(length)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCodeGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockCodeGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - length int
func (_e *MockCodeGenerator_Expecter) Generate(length interface{}) *MockCodeGenerator_Generate_Call {
	return &MockCodeGenerator_Generate_Call{Call: _e.mock.On("Generate", length)}
}

func (_c *MockCodeGenerator_Generate_Call) Run(run func(length int)) *MockCodeGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCodeGenerator_Generate_Call) Return(s string, err error) *MockCodeGenerator_Generate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCodeGenerator_Generate_Call) RunAndReturn(run func(length int) (string, error)) *MockCodeGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserStore creates a new instance of MockUserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserStore {
	mock := &MockUserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserStore is an autogenerated mock type for the UserStore type
type MockUserStore struct {
	mock.Mock
}

type MockUserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserStore) EXPECT() *MockUserStore_Expecter {
	return &MockUserStore_Expecter{mock: &_m.Mock}
}

// GetUserByAPIKey provides a mock function for the type MockUserStore
func (_mock *MockUserStore) GetUserByAPIKey(ctx context.Context, apiKey string) (*models.User, error) {
	ret := _mock.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByAPIKey")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, apiKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStore_GetUserByAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByAPIKey'
type MockUserStore_GetUserByAPIKey_Call struct {
	*mock.Call
}

// GetUserByAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey string
func (_e *MockUserStore_Expecter) GetUserByAPIKey(ctx interface{}, apiKey interface{}) *MockUserStore_GetUserByAPIKey_Call {
	return &MockUserStore_GetUserByAPIKey_Call{Call: _e.mock.On("GetUserByAPIKey", ctx, apiKey)}
}

func (_c *MockUserStore_GetUserByAPIKey_Call) Run(run func(ctx context.Context, apiKey string)) *MockUserStore_GetUserByAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserStore_GetUserByAPIKey_Call) Return(user *models.User, err error) *MockUserStore_GetUserByAPIKey_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserStore_GetUserByAPIKey_Call) RunAndReturn(run func(ctx context.Context, apiKey string) (*models.User, error)) *MockUserStore_GetUserByAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUser provides a mock function for the type MockUserStore
func (_mock *MockUserStore) SaveUser(ctx context.Context, user *models.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserStore_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type MockUserStore_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *MockUserStore_Expecter) SaveUser(ctx interface{}, user interface{}) *MockUserStore_SaveUser_Call {
	return &MockUserStore_SaveUser_Call{Call: _e.mock.On("SaveUser", ctx, user)}
}

func (_c *MockUserStore_SaveUser_Call) Run(run func(ctx context.Context, user *models.User)) *MockUserStore_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserStore_SaveUser_Call) Return(err error) *MockUserStore_SaveUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserStore_SaveUser_Call) RunAndReturn(run func(ctx context.Context, user *models.User) error) *MockUserStore_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}
