// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlers

import (
	"context"

	"github.com/dalibortosic00/url-shortener/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLinkDeleter creates a new instance of MockLinkDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinkDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinkDeleter {
	mock := &MockLinkDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLinkDeleter is an autogenerated mock type for the LinkDeleter type
type MockLinkDeleter struct {
	mock.Mock
}

type MockLinkDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLinkDeleter) EXPECT() *MockLinkDeleter_Expecter {
	return &MockLinkDeleter_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockLinkDeleter
func (_mock *MockLinkDeleter) Delete(ctx context.Context, code string, ownerID string) error {
	ret := _mock.Called(ctx, code, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, code, ownerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLinkDeleter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLinkDeleter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - ownerID string
func (_e *MockLinkDeleter_Expecter) Delete(ctx interface{}, code interface{}, ownerID interface{}) *MockLinkDeleter_Delete_Call {
	return &MockLinkDeleter_Delete_Call{Call: _e.mock.On("Delete", ctx, code, ownerID)}
}

func (_c *MockLinkDeleter_Delete_Call) Run(run func(ctx context.Context, code string, ownerID string)) *MockLinkDeleter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLinkDeleter_Delete_Call) Return(err error) *MockLinkDeleter_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLinkDeleter_Delete_Call) RunAndReturn(run func(ctx context.Context, code string, ownerID string) error) *MockLinkDeleter_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLinkLister creates a new instance of MockLinkLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinkLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinkLister {
	mock := &MockLinkLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLinkLister is an autogenerated mock type for the LinkLister type
type MockLinkLister struct {
	mock.Mock
}

type MockLinkLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLinkLister) EXPECT() *MockLinkLister_Expecter {
	return &MockLinkLister_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockLinkLister
func (_mock *MockLinkLister) List(ctx context.Context, ownerID string) ([]models.LinkRecord, error) {
	ret := _mock.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.LinkRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.LinkRecord, error)); ok {
		return returnFunc(ctx, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.LinkRecord); ok {
		r0 = returnFunc(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.LinkRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkLister_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockLinkLister_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
func (_e *MockLinkLister_Expecter) List(ctx interface{}, ownerID interface{}) *MockLinkLister_List_Call {
	return &MockLinkLister_List_Call{Call: _e.mock.On("List", ctx, ownerID)}
}

func (_c *MockLinkLister_List_Call) Run(run func(ctx context.Context, ownerID string)) *MockLinkLister_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkLister_List_Call) Return(linkRecords []models.LinkRecord, err error) *MockLinkLister_List_Call {
	_c.Call.Return(linkRecords, err)
	return _c
}

func (_c *MockLinkLister_List_Call) RunAndReturn(run func(ctx context.Context, ownerID string) ([]models.LinkRecord, error)) *MockLinkLister_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserCreator creates a new instance of MockUserCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserCreator {
	mock := &MockUserCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserCreator is an autogenerated mock type for the UserCreator type
type MockUserCreator struct {
	mock.Mock
}

type MockUserCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserCreator) EXPECT() *MockUserCreator_Expecter {
	return &MockUserCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserCreator
func (_mock *MockUserCreator) Create(ctx context.Context, name string) (string, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockUserCreator_Expecter) Create(ctx interface{}, name interface{}) *MockUserCreator_Create_Call {
	return &MockUserCreator_Create_Call{Call: _e.mock.On("Create", ctx, name)}
}

func (_c *MockUserCreator_Create_Call) Run(run func(ctx context.Context, name string)) *MockUserCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserCreator_Create_Call) Return(s string, err error) *MockUserCreator_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserCreator_Create_Call) RunAndReturn(run func(ctx context.Context, name string) (string, error)) *MockUserCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLinkResolver creates a new instance of MockLinkResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinkResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinkResolver {
	mock := &MockLinkResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLinkResolver is an autogenerated mock type for the LinkResolver type
type MockLinkResolver struct {
	mock.Mock
}

type MockLinkResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLinkResolver) EXPECT() *MockLinkResolver_Expecter {
	return &MockLinkResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type MockLinkResolver
func (_mock *MockLinkResolver) Resolve(ctx context.Context, code string) (string, bool) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, bool)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockLinkResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockLinkResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockLinkResolver_Expecter) Resolve(ctx interface{}, code interface{}) *MockLinkResolver_Resolve_Call {
	return &MockLinkResolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx, code)}
}

func (_c *MockLinkResolver_Resolve_Call) Run(run func(ctx context.Context, code string)) *MockLinkResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkResolver_Resolve_Call) Return(s string, b bool) *MockLinkResolver_Resolve_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockLinkResolver_Resolve_Call) RunAndReturn(run func(ctx context.Context, code string) (string, bool)) *MockLinkResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLinkCreator creates a new instance of MockLinkCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinkCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinkCreator {
	mock := &MockLinkCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLinkCreator is an autogenerated mock type for the LinkCreator type
type MockLinkCreator struct {
	mock.Mock
}

type MockLinkCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLinkCreator) EXPECT() *MockLinkCreator_Expecter {
	return &MockLinkCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockLinkCreator
func (_mock *MockLinkCreator) Create(ctx context.Context, url string, ownerID *string) (string, error) {
	ret := _mock.Called(ctx, url, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string) (string, error)); ok {
		return returnFunc(ctx, url, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string) string); ok {
		r0 = returnFunc(ctx, url, ownerID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string) error); ok {
		r1 = returnFunc(ctx, url, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLinkCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - ownerID *string
func (_e *MockLinkCreator_Expecter) Create(ctx interface{}, url interface{}, ownerID interface{}) *MockLinkCreator_Create_Call {
	return &MockLinkCreator_Create_Call{Call: _e.mock.On("Create", ctx, url, ownerID)}
}

func (_c *MockLinkCreator_Create_Call) Run(run func(ctx context.Context, url string, ownerID *string)) *MockLinkCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLinkCreator_Create_Call) Return(s string, err error) *MockLinkCreator_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLinkCreator_Create_Call) RunAndReturn(run func(ctx context.Context, url string, ownerID *string) (string, error)) *MockLinkCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCustom provides a mock function for the type MockLinkCreator
func (_mock *MockLinkCreator) CreateCustom(ctx context.Context, url string, customCode string, ownerID *string) (string, error) {
	ret := _mock.Called(ctx, url, customCode, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustom")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string) (string, error)); ok {
		return returnFunc(ctx, url, customCode, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string) string); ok {
		r0 = returnFunc(ctx, url, customCode, ownerID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *string) error); ok {
		r1 = returnFunc(ctx, url, customCode, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkCreator_CreateCustom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCustom'
type MockLinkCreator_CreateCustom_Call struct {
	*mock.Call
}

// CreateCustom is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - customCode string
//   - ownerID *string
func (_e *MockLinkCreator_Expecter) CreateCustom(ctx interface{}, url interface{}, customCode interface{}, ownerID interface{}) *MockLinkCreator_CreateCustom_Call {
	return &MockLinkCreator_CreateCustom_Call{Call: _e.mock.On("CreateCustom", ctx, url, customCode, ownerID)}
}

func (_c *MockLinkCreator_CreateCustom_Call) Run(run func(ctx context.Context, url string, customCode string, ownerID *string)) *MockLinkCreator_CreateCustom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLinkCreator_CreateCustom_Call) Return(s string, err error) *MockLinkCreator_CreateCustom_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLinkCreator_CreateCustom_Call) RunAndReturn(run func(ctx context.Context, url string, customCode string, ownerID *string) (string, error)) *MockLinkCreator_CreateCustom_Call {
	_c.Call.Return(run)
	return _c
}
